services:
    nginx-proxy:
      image: nginxproxy/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - "certs:/etc/nginx/certs"
        - "vhost:/etc/nginx/vhost.d"
        - "html:/usr/share/nginx/html"
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
      networks:
        - "bjoggis-home_default"
    nginx-proxy-acme:
      image: nginxproxy/acme-companion
      container_name: acme-companion
      volumes_from:
        - "nginx-proxy"
      networks:
        - "bjoggis-home_default"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "acme:/etc/acme.sh"
volumes:
  certs:
    external: true
  vhost:
    external: true
  html:
    external: true
  acme:
    external: true
networks:
  bjoggis-home_default:
    external: true
